/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.Produto;
import dao.ProdutoDAO;
import model.Usuario;



/**
 * TelaCadastroProduto.java
 * 
 * @author Anthony
 * 
 * 
 * Esta classe representa a interface gráfica para cadastro de Produtos
 * no sistema. Permite ao usuário inserir Descrição do produto / serviço ,
 * quantidade em estoque e valor unitario,além de limpar os 
 * campos ou retornar à tela anterior.
 * 
 * 
 * A tela é acessada por usuários logados, e a lógica de envio de dados
 * deve ser vinculada ao DAO correspondente.
 */


public class TelaCadastroProduto extends javax.swing.JFrame {
private Usuario usuario;
    /**
     * Creates new form TelaCadastroProduto
     */


/**
     * Construtor da tela de cadastro de produto ou serviço.
     * 
     * Este construtor recebe um objeto do tipo {@link Usuario} para manter o contexto
     * do usuário que acessou a tela, e inicializa os componentes da interface.
     * 
     * @param usuario o usuário logado no sistema
     */



    public TelaCadastroProduto(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTelaCadastroProdutos = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblDescricaoProdutoServico = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblQuantidadeEmEstoque = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        lblValorUnitario = new javax.swing.JLabel();
        txtValorUnitario = new javax.swing.JTextField();
        lblCamposObrigatrios = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        lblTelaCadastroProdutos.setBackground(new java.awt.Color(255, 255, 255));
        lblTelaCadastroProdutos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTelaCadastroProdutos.setForeground(new java.awt.Color(255, 255, 255));
        lblTelaCadastroProdutos.setText("CADASTRO DE PRODUTOS / SERVIÇOS ");
        lblTelaCadastroProdutos.setToolTipText("TELA CADASTRO DO PRODUTO / SERVIÇOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTelaCadastroProdutos)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(lblTelaCadastroProdutos)
                .addGap(19, 19, 19))
        );

        lblTelaCadastroProdutos.getAccessibleContext().setAccessibleParent(lblTelaCadastroProdutos);

        lblLogo.setBackground(new java.awt.Color(0, 0, 0));
        lblLogo.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        lblLogo.setText("GrafX");
        lblLogo.setToolTipText("LOGO GRAFX");

        lblDescricaoProdutoServico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescricaoProdutoServico.setText("DESCRIÇÃO DO PRODUTO / SERVIÇO*:");
        lblDescricaoProdutoServico.setToolTipText("INSIRA A DESCRIÇÃO DO PRODUTO ");

        lblQuantidadeEmEstoque.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuantidadeEmEstoque.setText("QUANTIDADE EM ESTOQUE*:");
        lblQuantidadeEmEstoque.setToolTipText("INSIRA QUANTIDADE EM ESTOQUE ");

        lblValorUnitario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblValorUnitario.setText("VALOR UNITÁRIO*:");
        lblValorUnitario.setToolTipText("INSIRA O VALOR UNITARIO ");

        lblCamposObrigatrios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCamposObrigatrios.setForeground(new java.awt.Color(255, 0, 0));
        lblCamposObrigatrios.setText("CAMPOS OBRIGATÓRIOS*");
        lblCamposObrigatrios.setToolTipText("CAMPOS OBRIGATORIOS ");

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setToolTipText("CLIQUE PARA VOLTAR ");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.setToolTipText("CLIQUE PARA LIMPAR ");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnEnviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnviar.setText("ENVIAR");
        btnEnviar.setToolTipText("CLIQUE PARA ENVIAR ");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblLogo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDescricaoProdutoServico)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuantidadeEmEstoque)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValorUnitario)
                                    .addComponent(txtValorUnitario)))
                            .addComponent(lblCamposObrigatrios, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblLogo)))
                .addGap(54, 54, 54)
                .addComponent(lblDescricaoProdutoServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantidadeEmEstoque)
                    .addComponent(lblValorUnitario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCamposObrigatrios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        lblLogo.getAccessibleContext().setAccessibleParent(lblLogo);
        lblCamposObrigatrios.getAccessibleContext().setAccessibleParent(lblCamposObrigatrios);
        btnVoltar.getAccessibleContext().setAccessibleParent(btnVoltar);
        btnLimpar.getAccessibleContext().setAccessibleParent(btnLimpar);
        btnEnviar.getAccessibleContext().setAccessibleParent(btnEnviar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**
     * Método responsável por enviar os dados preenchidos para cadastro.
     * Realiza validações e envia os dados para o DAO.
     * 
     * @param evt Evento de clique no botão "Enviar"
     */
    
    
    
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
    
    String descricao = txtDescricao.getText().trim();
    String quantidadeStr = txtQuantidade.getText().trim();
    String valorStr = txtValorUnitario.getText().trim();

    // Validação de campos obrigatórios
    if (descricao.isEmpty() || quantidadeStr.isEmpty() || valorStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validação de quantidade (somente números inteiros)
    int quantidade;
    try {
        quantidade = Integer.parseInt(quantidadeStr);
        if (quantidade < 0) {
            JOptionPane.showMessageDialog(this, "Quantidade deve ser um número positivo.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Quantidade deve conter apenas números inteiros.", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validação do valor unitário (formato XXX.XX)
    double valorUnitario;
    if (!valorStr.matches("\\d+\\.\\d{2}")) {
        JOptionPane.showMessageDialog(this, "Valor deve estar no formato XXX.XX (ex: 150.00)", "Erro", JOptionPane.ERROR_MESSAGE);
        return;
    }
    valorUnitario = Double.parseDouble(valorStr);

    // Criar e salvar produto
   Produto produto = new Produto();
produto.setDescricao(txtDescricao.getText());
produto.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
produto.setValorUnitario(Double.parseDouble(txtValorUnitario.getText()));

ProdutoDAO dao = new ProdutoDAO();
dao.cadastrarProduto(produto);


    limparCampos();

    }//GEN-LAST:event_btnEnviarActionPerformed

   /**
     * Método responsável por limpar todos os campos de entrada da tela.
     * Chamado ao clicar no botão "Limpar".
     * 
     * @param evt Evento de clique no botão "Limpar"
     */
     
    
    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

     /**
     * Método responsável por fechar a tela atual e retornar à anterior.
     * 
     * @param evt Evento de clique no botão "Voltar"
     */
    
    
    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
    TelaInicio inicio = new TelaInicio(usuario); // passe o usuário logado corretamente
    inicio.setVisible(true);
    dispose();  
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCamposObrigatrios;
    private javax.swing.JLabel lblDescricaoProdutoServico;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblQuantidadeEmEstoque;
    private javax.swing.JLabel lblTelaCadastroProdutos;
    private javax.swing.JLabel lblValorUnitario;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValorUnitario;
    // End of variables declaration//GEN-END:variables

    
    // Método responsável por limpar todos os campos de entrada da tela
    private void limparCampos() {
    txtDescricao.setText("");
    txtQuantidade.setText("");
    txtValorUnitario.setText("");
}

}
