
package view;


import model.Usuario;

/**
 * TelaInicio.java
 * 
 * @author Anthony
 * 
 * 
 * Esta classe representa a interface gráfica para acessar demais
 * telas do sistema; Tela de Cadastro de Clientes, Tela de Cadastro de Produtos,
 * Tela de Cadastro de Vendas, Tela de Cadastro Atendente e Tela de Busca.
 * Apenas o Administrador tem acesso a todas as telas, o Atendente tem 
 * o acesso restrito.
 * 
 *
 */




public class TelaInicio extends javax.swing.JFrame {
    private Usuario usuario;

    /**
     * Creates new form TelaInicio
     */
    
    
    
     //Construtor da tela inicial. Recebe o usuário logado e chama o método
     //que verifica as permissões de acesso aos botões
    
    public TelaInicio(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        verificaPermissoes();
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogoGrafx = new javax.swing.JLabel();
        btnCadastrarCliente = new javax.swing.JButton();
        btnCadastrarProduto = new javax.swing.JButton();
        btnCadastrarVenda = new javax.swing.JButton();
        btnCadastrarAtendente = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblLogoGrafx.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        lblLogoGrafx.setText("GrafX");
        lblLogoGrafx.setToolTipText("LOGO GRAFX");

        btnCadastrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrarCliente.setText("01 - CADASTRAR CLIENTE ");
        btnCadastrarCliente.setToolTipText("CLIQUE PARA CADASTRAR CLIENTE ");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        btnCadastrarProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrarProduto.setText("02 - CADASTRAR PRODUTO ");
        btnCadastrarProduto.setToolTipText("CLIQUE PARA CADASTRAR PRODUTO ");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        btnCadastrarVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrarVenda.setText("03 - CADASTRAR VENDA ");
        btnCadastrarVenda.setToolTipText("CLIQUE PARA CADASTRAR VENDA ");
        btnCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarVendaActionPerformed(evt);
            }
        });

        btnCadastrarAtendente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrarAtendente.setText("04 - CADASTRAR ATENDENTE ");
        btnCadastrarAtendente.setToolTipText("CLIQUE PARA CADASTRAR ATENDENTE ");
        btnCadastrarAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAtendenteActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("05 - BUSCAR ");
        btnBuscar.setToolTipText("CLIQUE PARA BUSCAR ");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSair.setText("SAIR ");
        btnSair.setToolTipText("CLIQUE PARA SAIR ");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(lblLogoGrafx))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrarAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblLogoGrafx)
                .addGap(43, 43, 43)
                .addComponent(btnCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        lblLogoGrafx.getAccessibleContext().setAccessibleParent(lblLogoGrafx);
        btnCadastrarCliente.getAccessibleContext().setAccessibleParent(btnCadastrarCliente);
        btnCadastrarProduto.getAccessibleContext().setAccessibleParent(btnCadastrarProduto);
        btnCadastrarVenda.getAccessibleContext().setAccessibleParent(btnCadastrarVenda);
        btnCadastrarAtendente.getAccessibleContext().setAccessibleParent(btnCadastrarAtendente);
        btnBuscar.getAccessibleContext().setAccessibleParent(btnBuscar);
        btnSair.getAccessibleContext().setAccessibleParent(btnSair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Abre a tela de cadastro de clientes
    
    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
    TelaCadastroCliente cadastroCliente = new TelaCadastroCliente(usuario);
    cadastroCliente.setVisible(true);
    dispose();;
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    //Abre a tela de cadastro de Produtos
    
    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
    TelaCadastroProduto tela = new TelaCadastroProduto(usuario);
    tela.setVisible(true);
    dispose();
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    //Abre a tela de cadastro de vendas
    
    private void btnCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarVendaActionPerformed
   TelaCadastroVenda tela = new TelaCadastroVenda(usuario);
   tela.setVisible(true);
   dispose();
    }//GEN-LAST:event_btnCadastrarVendaActionPerformed

    //Abre a tela de cadastro de atendentes
    
    private void btnCadastrarAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAtendenteActionPerformed
    TelaCadastroAtendente tela = new TelaCadastroAtendente(usuario);
    tela.setVisible(true);
    dispose();
    }//GEN-LAST:event_btnCadastrarAtendenteActionPerformed

    //Abre a tela de busca
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    TelaBusca tela = new TelaBusca(usuario);
    tela.setVisible(true);
    dispose();
    }//GEN-LAST:event_btnBuscarActionPerformed

    //Encerra a aplicação quando o botão "Sair" for clicado
    
    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrarAtendente;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnCadastrarVenda;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogoGrafx;
    // End of variables declaration//GEN-END:variables

   
    //Verifica o tipo de usuário logado e ajusta as permissões de acesso aos botões.

    private void verificaPermissoes() {
        if (usuario.getTipoUsuario().equalsIgnoreCase("Atendente")) {
        btnCadastrarProduto.setEnabled(false);
        btnCadastrarAtendente.setEnabled(false);
    }
    }
}
